
/* -------------------- INSERT LEVEL -------------------- */
INSERT INTO LEVEL(LVL_LABEL, LVL_MAIN_PICTURE,LVL_XP_MIN,LVL_XP_MAX, LVL_NUM) VALUES('Nouveau cuisinier',null, 0, 500, 1);
INSERT INTO LEVEL(LVL_LABEL, LVL_MAIN_PICTURE,LVL_XP_MIN,LVL_XP_MAX, LVL_NUM) VALUES('Casseur d oeuf',null, 501, 1001, 2);
INSERT INTO LEVEL(LVL_LABEL, LVL_MAIN_PICTURE,LVL_XP_MIN,LVL_XP_MAX, LVL_NUM) VALUES( 'Cuisinier toqué',null, 1002, 1502, 3);
INSERT INTO LEVEL(LVL_LABEL, LVL_MAIN_PICTURE,LVL_XP_MIN,LVL_XP_MAX, LVL_NUM) VALUES( 'Commis de cuisine',null, 1503, 2003, 4);
INSERT INTO LEVEL(LVL_LABEL, LVL_MAIN_PICTURE,LVL_XP_MIN,LVL_XP_MAX, LVL_NUM) VALUES( 'Chef étoilé',null, 2004, 100000, 5);


/* -------------------- INSERT MEMBER -------------------- */
INSERT INTO MEMBER(mbr_id_member, MBR_USERNAME,MBR_EMAIL,MBR_PASSWORD) VALUES(1,'user','user@user.be','user');
INSERT INTO MEMBER(mbr_id_member, MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_BIRTHDAY,
MBR_GENDER,MBR_CITY,
MBR_LEVEL, MBR_EXPERIENCE) VALUES(2,'dufaux','johan','dufaux','johan.dufaux@etudiant.univ-lille1.fr','MBR_PASSWORD',
'1993-05-28','M','Lille',3 , 350);
INSERT INTO MEMBER(mbr_id_member, MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_BIRTHDAY,
MBR_GENDER,MBR_CITY,
MBR_LEVEL, MBR_EXPERIENCE) VALUES(3,'cookorico','cookorico','cookorico','cookorico@yopmail.com','cookorico',
'2015-08-31','M','Villeneuve d''Ascq',3 , 350);
INSERT INTO MEMBER(mbr_id_member, MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_BIRTHDAY,
MBR_GENDER,MBR_CITY,
MBR_LEVEL, MBR_EXPERIENCE) VALUES(4,'Dieulin','Dieulin','Mambouana','dieulin@cookorico.com','Dieulin','2015-08-31',
'M','Villeneuve d''Ascq',3 , 350);
INSERT INTO MEMBER(mbr_id_member, MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_BIRTHDAY,
MBR_GENDER,MBR_CITY,
MBR_LEVEL, MBR_EXPERIENCE) VALUES(5,'Ly4m','William','Leemans','Ly4m@cookorico.com','Ly4m','1993-07-04','M',
'Villeneuve d''Ascq',3 , 350);
INSERT INTO MEMBER(mbr_id_member, MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_GENDER) VALUES
(6,'Mandrivia',
'Antoine','Philippe','Mandrivia@cookorico.com','Mandrivia','M');
INSERT INTO MEMBER(mbr_id_member, MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_GENDER, MBR_LEVEL,
MBR_EXPERIENCE) VALUES(7,'ouams','Ouamar','Sais','ouams@gmail.com','ouams','M', 3, 350);
INSERT INTO MEMBER(mbr_id_member, MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_GENDER) VALUES
(8,'sallareznov',
'Salla','Diagne','sallareznov@cookorico.com','sallareznov','M');
INSERT INTO MEMBER(mbr_id_member, MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_GENDER) VALUES
(9,'sofianekabylino','Sofiane','Yousfi','sofianekabylino@cookorico.com','sofianekabylino','M');


/* -------------------- INSERT PRODUCER -------------------- */
INSERT INTO PRODUCER(prd_id_producer, PRD_CITY, PRD_NAME, PRD_DESCRIPTION, PRD_PICPATH) VALUES
(1,'Lille',
'Ouamar','Un producteur de carottes incroyable', 'images/producteur1.png');
INSERT INTO PRODUCER(prd_id_producer, PRD_CITY, PRD_NAME, PRD_DESCRIPTION, PRD_PICPATH) VALUES
(2,'Lille',
'Johan','Un producteur toujours souriant', 'images/producteur2.png');
INSERT INTO PRODUCER(prd_id_producer, PRD_CITY, PRD_NAME, PRD_DESCRIPTION, PRD_PICPATH) VALUES
(3,'Lille',
'Antoine','Un producteur parfois nerveux', 'images/producteur3.png');
INSERT INTO PRODUCER(prd_id_producer, PRD_CITY, PRD_NAME, PRD_DESCRIPTION, PRD_PICPATH) VALUES
(4,'Bruxelles',
'Will','Un producteur de pommes de terre reconnu', 'images/producteur4.png');


/* -------------------- INSERT INGREDIENT -------------------- */
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(1,'Banane','Fruit courbé et de couleur jaune');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(2,'Citron','Fruit presque rond et de couleur
jaune');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(3,'Viande hachée','De la viande, hachée... et de
boeuf... (sauf pour les chinois)');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(4,'Pied de porc','Pour ceux qui aiment');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(5,'Oeuf','Un truc ovale et qui sort d''on ne sait
où');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(6,'Sel','Du sel');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(7,'Sucre','Du sucre');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(8,'Poivre','Du poivre');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(9,'Huile d''Olive','De l''huile qui vient des
olives');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(10,'Beurre','Du beurre, les produits laitiers sont
nos amis pour la vie');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(11, 'Farine','Farine de blé');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(12, 'Beurre salé','Du beurre, les produits
laitiers sont
nos amis pour la vie');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(13,'Lait','Lait de vache');
INSERT INTO INGREDIENT(igd_id_ingredient,IGD_NAME,IGD_DESCRIPTION) VALUES(14,'Huile','Huile de cuisine');




/* -------------------- INSERT TAG -------------------- */
/* TYPE TAG_TYPE AS ENUM ('Origine','Type de nourriture','Saveur') */
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Sucré','Saveur');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Salé','Saveur');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Amer','Saveur');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Acide','Saveur');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Umami','Saveur');

INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Végétarien','Type de nourriture');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Végétalien','Type de nourriture');

INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Italien','Origine');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Japonais','Origine');

INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Agrume','Type de nourriture');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Boeuf','Type de nourriture');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Porc','Type de nourriture');





/* -------------------- INSERT TASTE -------------------- */
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('3','1','9');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('3','2','6');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('3','3','10');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('3','4','1');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('3','5','6');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('3','8','8');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('3','9','9');



/* -------------------- INSERT RECIPE -------------------- */
/* CREATE TYPE DISH_TYPE AS ENUM ('Dessert','Entree','Plat') */
/* CREATE TYPE DIFFICULTY AS ENUM ('Facile','Moyen','Difficile') */
INSERT INTO RECIPE(RCP_NAME,RCP_DESCRIPTION,RCP_PREPARATION_TIME,RCP_COOKING_TIME,RCP_FK_CREATOR,RCP_DISH_TYPE,RCP_DIFFICULTY, RCP_EXPERIENCE_VAL) VALUES('Omelette','Une superbe omelette baveuse',300,360,1,'Plat',0, 10);
INSERT INTO RECIPE(RCP_NAME,RCP_DESCRIPTION,RCP_PREPARATION_TIME,RCP_COOKING_TIME,RCP_FK_CREATOR,RCP_DISH_TYPE,RCP_DIFFICULTY, RCP_EXPERIENCE_VAL) VALUES('Pizza','Pizza Orientale',300,360,1,'Plat',1, 20);
INSERT INTO RECIPE(RCP_NAME,RCP_DESCRIPTION,RCP_PREPARATION_TIME,RCP_COOKING_TIME,RCP_FK_CREATOR,RCP_DISH_TYPE,
RCP_DIFFICULTY, RCP_EXPERIENCE_VAL) VALUES('Crêpes','Pâte à crêpes',600,1200,6,'Dessert',1, 10);


/*
1 banane, 2 citron, 3 viande hachée, 4 pied de pord, 5 oeuf, 6 sel, 7 sucre, 8 poivre, 9 huile d'olive, 10 beurre pomme
*/
/*
1sucré, 2salé, 3amer, 4acide, 5umami, 6végétarien, 7végétalien, 8italien, 9japonais, 10agrume, 11boeuf, 12porc
*/
/* -------------------- INSERT TAG_TO_INGREDIENT -------------------- */
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('1','1');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('1','6');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('1','7');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('2','4');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('2','6');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('2','7');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('2','10');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('3','11');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('4','12');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('5','6');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('6','2');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('6','6');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('6','7');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('7','6');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('7','7');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('9','6');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('9','7');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_INGREDIENT,TTI_FK_ID_TAG) VALUES('10','6');



/* -------------------- INSERT INGREDIENT_IN_RECIPE -------------------- */
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('5','1',
3,'unité(s)');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('6','1',
4,'gramme(s)');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('8','1',2,'gramme(s)');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('8','1',2,'gramme(s)');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('5','3',
3,'unité(s)');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('5','3',3,'unité(s)');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('11','3',300,'gramme(s)');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('7','3',
3,'cuillère(s) à soupe');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('11','3',300,'gramme(s)');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('11','3',300,'gramme(s)');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('14','3',
2,'cuillère(s) à soupe');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('12','3',50,'gramme(s)');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('13','3',
30,'centilitre(s)');





/* -------------------- INSERT PHOTO  -------------------- */



/* -------------------- INSERT RECIPE_STEP -------------------- */
INSERT INTO RECIPE_STEP(RST_FK_ID_RECIPE,RST_RANK,RST_NAME,RST_DESCRIPTION,RST_DURATION_TIME) VALUES(1,1,'Preparation','Battre les oeufs dans un saladier',180);
INSERT INTO RECIPE_STEP(RST_FK_ID_RECIPE,RST_RANK,RST_NAME,RST_DESCRIPTION,RST_DURATION_TIME) VALUES(1,2,'Assaisonner','Ajouter sel et poivre à votre convenance',100);
INSERT INTO RECIPE_STEP(RST_FK_ID_RECIPE,RST_RANK,RST_NAME,RST_DESCRIPTION,RST_DURATION_TIME) VALUES(1,3,'Verser','Verser les oeufs dans une poele chaude',20);
INSERT INTO RECIPE_STEP(RST_FK_ID_RECIPE,RST_RANK,RST_NAME,RST_DESCRIPTION,RST_DURATION_TIME) VALUES(1,4,'Cuisson','Quand les bords coagulent, les rabattre vers le centre. <br> Une fois l''omelette cuite, la servir dans une assiette. ',300);

INSERT INTO RECIPE_STEP(RST_FK_ID_RECIPE,RST_RANK,RST_NAME,RST_DESCRIPTION,RST_DURATION_TIME) VALUES(3,4,'Preparation','Mettre la farine dans une terrine et former un puits. Mettre les œufs entiers, le sucre, l''huile et le beurre.',300);
INSERT INTO RECIPE_STEP(RST_FK_ID_RECIPE,RST_RANK,RST_NAME,RST_DESCRIPTION,RST_DURATION_TIME) VALUES(3,4,'Preparation','Mélanger délicatement avec un fouet en ajoutant au fur et à mesure le lait. La pâte ainsi obtenue doit avoir une consistance d''un liquide légèrement épais. ',300);
INSERT INTO RECIPE_STEP(RST_FK_ID_RECIPE,RST_RANK,RST_NAME,RST_DESCRIPTION,RST_DURATION_TIME) VALUES(3,4,'Cuisson','Faire chauffer une poêle anti-adhésive et y déposer quelques gouttes d''huile. Faire cuire les crêpes à feu doux.',600);




/* -------------------- INSERT TAG_TO_RECIPE -------------------- */
INSERT INTO TAG_TO_RECIPE(TTR_FK_ID_TAG,TTR_FK_ID_RECIPE) VALUES('6','1');




/* -------------------- INSERT COMMENT -------------------- */

INSERT INTO COMMENT(CMT_FK_ID_RECIPE,CMT_FK_ID_MEMBER,CMT_TITLE,CMT_DESCRIPTION) VALUES('1','8','NON!','J''aime pas
baveuse. nul!');
INSERT INTO COMMENT(CMT_FK_ID_RECIPE,CMT_FK_ID_MEMBER,CMT_TITLE,CMT_DESCRIPTION) VALUES('1','7','OSEF','Mdr t''as
qu''à la laisser plus longtemps');
INSERT INTO COMMENT(CMT_FK_ID_RECIPE,CMT_FK_ID_MEMBER,CMT_TITLE,CMT_DESCRIPTION) VALUES('2','6','bien','bono bono');

/* -------------------- INSERT NOTE -------------------- */
INSERT INTO NOTE(NOT_FK_ID_MEMBER,NOT_FK_ID_RECIPE,NOT_FK_ID_COMMENT,NOT_RATING) VALUES('2','1','2',2);


/* -------------------- INSERT PICTURE_IN_RECIPE -------------------- */

/* -------------------- INSERT ADMINISTRATOR -------------------- */

/* CREATE TYPE ADMIN_RANK AS ENUM ('Administrateur','Moderateur') */
INSERT INTO ADMINISTRATOR(ADM_ID_ADMINISTRATOR,ADM_RANK) VALUES(3,'Administrateur');
INSERT INTO ADMINISTRATOR(ADM_ID_ADMINISTRATOR,ADM_RANK) VALUES(2,'Moderateur');

/* -------------------- INSERT PICTURE_OF_INGREDIENT -------------------- */

/* -------------------- INSERT PICTURE_OF_USER -------------------- */

