

/* -------------------- INSERT MEMBER -------------------- */
INSERT INTO MEMBER(MBR_USERNAME,MBR_EMAIL,MBR_PASSWORD) VALUES('user','user@user.be','test');
INSERT INTO MEMBER(MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_SALT,MBR_BIRTHDAY,MBR_GENDER,MBR_CITY) VALUES('dufaux','johan','dufaux','johan.dufaux@etudiant.univ-lille1.fr','MBR_PASSWORD','MBR_SALT','1993-05-28','M','Lille');
INSERT INTO MEMBER(MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_SALT,MBR_BIRTHDAY,MBR_GENDER,MBR_CITY) VALUES('cookorico','cookorico','cookorico','cookorico@yopmail.com','cookorico','MBR_SALT','2015-08-31','M','Villeneuve d''Ascq');
INSERT INTO MEMBER(MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_GENDER) VALUES('Dieulin','Dieulin','Mambouana','dieulin@cookorico.com','Dieulin','M');
INSERT INTO MEMBER(MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_GENDER) VALUES('Ly4m','William','Leemans','Ly4m@cookorico.com','Ly4m','M');
INSERT INTO MEMBER(MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_GENDER) VALUES('Mandrivia','Antoine','Philippe','Mandrivia@cookorico.com','Mandrivia','M');
INSERT INTO MEMBER(MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_GENDER, LEVEL, EXPERIENCE) VALUES('ouams','Ouamar','Sais','ouams@gmail.com','ouams','M', 3, 350);
INSERT INTO MEMBER(MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_GENDER) VALUES('sallareznov','Salla','Diagne','sallareznov@cookorico.com','sallareznov','M');
INSERT INTO MEMBER(MBR_USERNAME,MBR_FIRSTNAME,MBR_LASTNAME,MBR_EMAIL,MBR_PASSWORD,MBR_GENDER) VALUES('sofianekabylino','Sofiane','Yousfi','sofianekabylino@cookorico.com','sofianekabylino','M');

/* -------------------- INSERT LEVEL -------------------- */
INSERT INTO LEVEL(LVL_LABEL, LVL_MAIN_PICTURE,LVL_XP_MIN,LVL_XP_MAX) VALUES('Nouveau cuisinier',1, 0, 50);
INSERT INTO LEVEL(LVL_LABEL, LVL_MAIN_PICTURE,LVL_XP_MIN,LVL_XP_MAX) VALUES('Casseur d oeuf',1, 50, 100);
INSERT INTO LEVEL(LVL_LABEL, LVL_MAIN_PICTURE,LVL_XP_MIN,LVL_XP_MAX) VALUES( 'Cuisinier toqué',1, 100, 200);
INSERT INTO LEVEL(LVL_LABEL, LVL_MAIN_PICTURE,LVL_XP_MIN,LVL_XP_MAX) VALUES( 'Commis de cuisine',1, 200, 350);
INSERT INTO LEVEL(LVL_LABEL, LVL_MAIN_PICTURE,LVL_XP_MIN,LVL_XP_MAX) VALUES( 'Chef étoilé',1, 1000, 1200);



/* -------------------- INSERT INGREDIENT -------------------- */
INSERT INTO INGREDIENT(IGD_NAME,IGD_DESCRIPTION) VALUES('Banane','Fruit courbé et de couleur jaune');
INSERT INTO INGREDIENT(IGD_NAME,IGD_DESCRIPTION) VALUES('Citron','Fruit presque rond et de couleur jaune');
INSERT INTO INGREDIENT(IGD_NAME,IGD_DESCRIPTION) VALUES('Viande hachée','De la viande, hachée... et de boeuf... (sauf pour les chinois)');
INSERT INTO INGREDIENT(IGD_NAME,IGD_DESCRIPTION) VALUES('Pied de porc','Pour ceux qui aiment');
INSERT INTO INGREDIENT(IGD_NAME,IGD_DESCRIPTION) VALUES('Oeuf','Un truc ovale et qui sort d''on ne sait où');
INSERT INTO INGREDIENT(IGD_NAME,IGD_DESCRIPTION) VALUES('Sel','Du sel');
INSERT INTO INGREDIENT(IGD_NAME,IGD_DESCRIPTION) VALUES('Sucre','Du sucre');
INSERT INTO INGREDIENT(IGD_NAME,IGD_DESCRIPTION) VALUES('Poivre','Du poivre');
INSERT INTO INGREDIENT(IGD_NAME,IGD_DESCRIPTION) VALUES('Huile d''Olive','De l''huile qui vient des olives');
INSERT INTO INGREDIENT(IGD_NAME,IGD_DESCRIPTION) VALUES('Beurre','Du beurre, les produits laitiers sont nos amis pour la vie');




/* -------------------- INSERT TAG -------------------- */
/* TYPE TAG_TYPE AS ENUM ('Origine','Type de nourriture','Saveur') */
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Sucré','Saveur');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Salé','Saveur');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Amer','Saveur');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Acide','Saveur');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Umami','Saveur');

INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Végétarien','Type de nourriture');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Végétalien','Type de nourriture');

INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Italien','Origine');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Japonais','Origine');

INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Agrume','Type de nourriture');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Boeuf','Type de nourriture');
INSERT INTO TAG(TAG_NAME,TAG_TYPE) VALUES('Porc','Type de nourriture');





/* -------------------- INSERT TASTE -------------------- */
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('10','11','9');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('10','15','6');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('10','14','10');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('10','12','1');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('12','11','6');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('12','12','8');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('12','13','9');
INSERT INTO TASTE(TST_FK_ID_MEMBER,TST_FK_ID_INGREDIENT,TST_GRADING) VALUES('12','13','0');




/* -------------------- INSERT RECIPE -------------------- */
/* CREATE TYPE DISH_TYPE AS ENUM ('Dessert','Entree','Plat') */
/* CREATE TYPE DIFFICULTY AS ENUM ('Facile','Moyen','Difficile') */
INSERT INTO RECIPE(RCP_NAME,RCP_DESCRIPTION,RCP_PREPARATION_TIME,RCP_COOKING_TIME,RCP_FK_CREATOR,RCP_DISH_TYPE,RCP_DIFFICULTY, RCP_EXPERIENCE_VAL) VALUES('Omelette','Une superbe omelette baveuse',300,360,10,'Plat',0, 10);




/* -------------------- INSERT TAG_TO_INGREDIENT -------------------- */
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('13','11');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('24','16');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('14','12');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('16','11');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('16','20');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('16','15');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('16','16');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('16','17');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('16','18');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('16','19');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('16','20');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('17','11');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('17','12');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('17','16');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('17','17');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('17','18');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('17','19');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('13','20');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('21','13');
INSERT INTO TAG_TO_INGREDIENT(TTI_FK_ID_TAG,TTI_FK_ID_INGREDIENT) VALUES('22','14');




/* -------------------- INSERT INGREDIENT_IN_RECIPE -------------------- */
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('15','1',3,'nombre');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('16','1',4,'gramme');
INSERT INTO INGREDIENT_IN_RECIPE(IIR_FK_ID_INGREDIENT,IIR_FK_ID_RECIPE,IIR_QUANTITY,IIR_MEASUREMENT) VALUES('18','1',2,'gramme');



/* -------------------- INSERT PHOTO  -------------------- */



/* -------------------- INSERT RECIPE_STEP -------------------- */
INSERT INTO RECIPE_STEP(RST_FK_ID_RECIPE,RST_RANK,RST_NAME,RST_DESCRIPTION,RST_DURATION_TIME) VALUES(1,1,'Preparation','Battre les oeufs dans un saladier',180);
INSERT INTO RECIPE_STEP(RST_FK_ID_RECIPE,RST_RANK,RST_NAME,RST_DESCRIPTION,RST_DURATION_TIME) VALUES(1,2,'Assaisonner','Ajouter sel et poivre à votre convenance',100);
INSERT INTO RECIPE_STEP(RST_FK_ID_RECIPE,RST_RANK,RST_NAME,RST_DESCRIPTION,RST_DURATION_TIME) VALUES(1,3,'Verser','Verser les oeufs dans une poele chaude',20);
INSERT INTO RECIPE_STEP(RST_FK_ID_RECIPE,RST_RANK,RST_NAME,RST_DESCRIPTION,RST_DURATION_TIME) VALUES(1,4,'Cuisson','Quand les bords coagulent, les rabattre vers le centre. <br> Une fois l''omelette cuite, la servir dans une assiette. ',300);




/* -------------------- INSERT TAG_TO_RECIPE -------------------- */
INSERT INTO TAG_TO_RECIPE(TTR_FK_ID_TAG,TTR_FK_ID_RECIPE) VALUES('16','1');




/* -------------------- INSERT COMMENT -------------------- */
INSERT INTO COMMENT(CMT_FK_ID_RECIPE,CMT_FK_ID_MEMBER,CMT_TITLE,CMT_DESCRIPTION) VALUES('1','12','NON!','J''aime pas baveuse. nul!');
INSERT INTO COMMENT(CMT_FK_ID_RECIPE,CMT_FK_ID_MEMBER,CMT_TITLE,CMT_DESCRIPTION) VALUES('1','11','OSEF','Mdr t''as qu''à la laisser plus longtemps');




/* -------------------- INSERT NOTE -------------------- */
INSERT INTO NOTE(NOT_FK_ID_MEMBER,NOT_FK_ID_RECIPE,NOT_FK_ID_COMMENT,NOT_RATING) VALUES('12','1','2',2)






/* -------------------- INSERT PICTURE_IN_RECIPE -------------------- */




/* -------------------- INSERT ADMINISTRATOR -------------------- */
/* CREATE TYPE ADMIN_RANK AS ENUM ('Administrateur','Moderateur') */
INSERT INTO ADMINISTRATOR(ADM_ID_ADMINISTRATOR,ADM_RANK) VALUES(13,'Administrateur');
INSERT INTO ADMINISTRATOR(ADM_ID_ADMINISTRATOR,ADM_RANK) VALUES(12,'Moderateur');




/* -------------------- INSERT PICTURE_OF_INGREDIENT -------------------- */




/* -------------------- INSERT PICTURE_OF_USER -------------------- */













